# Generated by Django 5.2.8 on 2025-11-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfirmation',
            name='code',
            field=models.CharField(max_length=4),
        ),
    ]
