# Generated by Django 5.2.8 on 2025-11-17 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_userconfirmation_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='post_id',
            new_name='post',
        ),
    ]
